"""RotoMath — Control Panel

A local web UI for configuring, launching, and monitoring the RotoMath service.
Opens in the user's browser. Handles API key entry, Google OAuth connection, and
displays a live log of all discrepancy alerts.
"""

import os
import sys
import json
import threading
import webbrowser
import logging
from datetime import datetime
from pathlib import Path

from flask import Flask, render_template_string, request, jsonify, Response
import queue

# ---------------------------------------------------------------------------
# Globals
# ---------------------------------------------------------------------------
BASE_DIR = Path(__file__).parent.resolve()
ENV_PATH = BASE_DIR / ".env"
ALERTS_PATH = BASE_DIR / "logs" / "alerts.json"

app = Flask(__name__)
monitor_thread: threading.Thread | None = None
monitor_running = False
stop_event = threading.Event()

# Server-Sent Events queue for live log streaming
log_queue: queue.Queue = queue.Queue()

# ---------------------------------------------------------------------------
# Alert persistence
# ---------------------------------------------------------------------------

def _load_alerts() -> list[dict]:
    if ALERTS_PATH.exists():
        try:
            return json.loads(ALERTS_PATH.read_text())
        except (json.JSONDecodeError, OSError):
            return []
    return []


def _save_alerts(alerts: list[dict]):
    ALERTS_PATH.parent.mkdir(parents=True, exist_ok=True)
    ALERTS_PATH.write_text(json.dumps(alerts, indent=2))


def record_alert(invoice) -> None:
    """Called by the monitoring loop when a discrepancy is found."""
    alerts = _load_alerts()
    entry = {
        "timestamp": datetime.now().isoformat(),
        "freelancer": invoice.freelancer_name,
        "invoice_number": invoice.invoice_number or "N/A",
        "stated_total": invoice.stated_total,
        "calculated_total": invoice.calculated_total,
        "discrepancy_amount": invoice.discrepancy_amount,
        "line_items": invoice.line_items,
        "source_email": invoice.source_email,
        "attachment": invoice.attachment_name or "Email body",
    }
    alerts.insert(0, entry)  # newest first
    _save_alerts(alerts)

    # Push to live stream
    log_queue.put(entry)


# ---------------------------------------------------------------------------
# Custom log handler that pushes to SSE queue
# ---------------------------------------------------------------------------

class QueueLogHandler(logging.Handler):
    def emit(self, record):
        try:
            log_queue.put({
                "type": "log",
                "timestamp": datetime.now().isoformat(),
                "level": record.levelname,
                "message": self.format(record),
            })
        except Exception:
            pass


# ---------------------------------------------------------------------------
# Environment / config helpers
# ---------------------------------------------------------------------------

def _read_env() -> dict:
    """Read the .env file into a dict."""
    env = {}
    if ENV_PATH.exists():
        for line in ENV_PATH.read_text().splitlines():
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" in line:
                k, v = line.split("=", 1)
                env[k.strip()] = v.strip()
    return env


def _write_env(env: dict):
    """Write a dict back to the .env file."""
    lines = []
    lines.append("# RotoMath configuration")
    lines.append("# Generated by Control Panel\n")
    for k, v in env.items():
        lines.append(f"{k}={v}")
    ENV_PATH.write_text("\n".join(lines) + "\n")


def _get_setup_status() -> dict:
    """Check what's configured and what's missing."""
    env = _read_env()
    creds_path = env.get("GOOGLE_CREDENTIALS_PATH", "credentials/google-credentials.json")
    creds_exists = (BASE_DIR / creds_path).exists()

    token_invoice = (BASE_DIR / "token" / "token-invoice.json").exists()
    token_kevin = (BASE_DIR / "token" / "token-kevin.json").exists()

    return {
        "anthropic_key": bool(env.get("ANTHROPIC_API_KEY", "").strip()),
        "google_creds_file": creds_exists,
        "inbox_1": env.get("INBOX_1_EMAIL", ""),
        "inbox_2": env.get("INBOX_2_EMAIL", ""),
        "token_invoice": token_invoice,
        "token_kevin": token_kevin,
        "sheet_invoice": bool(env.get("SHEET_ID_INVOICE", "").strip()),
        "sheet_kevin": bool(env.get("SHEET_ID_KEVIN", "").strip()),
        "poll_interval": env.get("POLL_INTERVAL_MINUTES", "5"),
        "all_required": (
            bool(env.get("ANTHROPIC_API_KEY", "").strip())
            and creds_exists
            and bool(env.get("INBOX_1_EMAIL", "").strip())
            and bool(env.get("INBOX_2_EMAIL", "").strip())
        ),
    }


# ---------------------------------------------------------------------------
# Monitor thread
# ---------------------------------------------------------------------------

def _run_monitor():
    """Run the invoice monitoring loop in a background thread."""
    global monitor_running
    monitor_running = True
    stop_event.clear()

    try:
        # Ensure logs directory exists
        os.makedirs(BASE_DIR / "logs", exist_ok=True)

        # Set up logging with our queue handler
        logger = logging.getLogger("invoice_monitor")
        logger.setLevel(logging.INFO)

        # File handler
        fh = logging.FileHandler(BASE_DIR / "logs" / "invoice_monitor.log")
        fh.setFormatter(logging.Formatter("%(asctime)s [%(levelname)s] %(name)s: %(message)s"))
        logger.addHandler(fh)

        # Queue handler for live UI
        qh = QueueLogHandler()
        qh.setFormatter(logging.Formatter("%(asctime)s [%(levelname)s] %(message)s"))
        logger.addHandler(qh)

        # Console handler
        ch = logging.StreamHandler()
        ch.setFormatter(logging.Formatter("%(asctime)s [%(levelname)s] %(message)s"))
        logger.addHandler(ch)

        # Change to project directory so relative paths work
        os.chdir(BASE_DIR)

        # Force re-read of .env
        from dotenv import load_dotenv
        load_dotenv(ENV_PATH, override=True)

        # Re-import config to pick up fresh env vars
        if "config" in sys.modules:
            del sys.modules["config"]
        import config as cfg

        from services.gmail_service import GmailService
        from services.sheets_service import SheetsService
        from services.extractor import extract_invoice_data
        from services.validator import validate_invoice
        from services.notifier import send_discrepancy_alerts
        from parsers.email_body_parser import extract_email_body
        from parsers.docx_parser import extract_docx_text
        from parsers.excel_parser import extract_excel_text

        gmail = GmailService()
        sheets = SheetsService()

        logger.info("=" * 50)
        logger.info("  RotoMath started via Control Panel")
        logger.info(f"  Inbox 1: {cfg.INBOX_1_EMAIL}")
        logger.info(f"  Inbox 2: {cfg.INBOX_2_EMAIL}")
        logger.info(f"  Poll interval: {cfg.POLL_INTERVAL_MINUTES} minutes")
        logger.info("=" * 50)

        while not stop_event.is_set():
            logger.info(f"=== Monitoring cycle: {datetime.now().isoformat()} ===")

            sheet_ids = sheets.ensure_spreadsheets_exist()

            for account in ["invoice", "kevin"]:
                if stop_event.is_set():
                    break
                try:
                    sheet_id = sheet_ids.get(account, "")
                    if not sheet_id:
                        logger.error(f"No sheet ID for {account} — skipping")
                        continue

                    logger.info(f"--- Processing inbox: {account} ---")
                    messages = gmail.get_unread_messages(account)
                    if not messages:
                        continue

                    for message in messages:
                        if stop_event.is_set():
                            break

                        message_id = message["id"]
                        subject = gmail.get_message_subject(message)
                        logger.info(f"Processing: {subject} (ID: {message_id})")

                        try:
                            body_text = extract_email_body(message.get("payload", {}))

                            attachment_texts = []
                            attachment_name = ""
                            attachments = gmail.get_attachments(account, message)

                            for att in attachments:
                                filename = att["filename"]
                                data = att["data"]
                                ext = os.path.splitext(filename)[1].lower()

                                if ext in (".docx", ".doc"):
                                    parsed = extract_docx_text(data)
                                elif ext in (".xlsx", ".xls"):
                                    parsed = extract_excel_text(data)
                                else:
                                    continue

                                if parsed and not parsed.startswith("[ERROR]"):
                                    attachment_texts.append(parsed)
                                    attachment_name = filename

                            combined_text = body_text
                            if attachment_texts:
                                combined_text += "\n\n--- ATTACHMENT ---\n\n" + "\n\n".join(attachment_texts)

                            if not combined_text.strip():
                                gmail.mark_as_read(account, message_id)
                                continue

                            invoice = extract_invoice_data(
                                raw_text=combined_text,
                                source_email=cfg.INBOX_1_EMAIL if account == "invoice" else cfg.INBOX_2_EMAIL,
                                attachment_name=attachment_name,
                            )

                            if not invoice:
                                gmail.mark_as_read(account, message_id)
                                continue

                            invoice = validate_invoice(invoice)
                            sheets.append_invoice(invoice, sheet_id, message_id=message_id)

                            if invoice.has_discrepancy:
                                send_discrepancy_alerts(invoice, gmail, account, message)
                                record_alert(invoice)
                                logger.warning(
                                    f"ALERT: Discrepancy for {invoice.freelancer_name} "
                                    f"(${invoice.discrepancy_amount:.2f})"
                                )

                            gmail.mark_as_read(account, message_id)
                            status = "DISCREPANCY" if invoice.has_discrepancy else "OK"
                            logger.info(f"Done: {invoice.freelancer_name} — ${invoice.stated_total:.2f} — {status}")

                        except Exception as e:
                            logger.error(f"Error processing {message_id}: {e}", exc_info=True)
                            gmail.mark_as_read(account, message_id)

                except Exception as e:
                    logger.error(f"Error processing {account} inbox: {e}", exc_info=True)

            logger.info("=== Cycle complete ===")

            # Wait for next cycle or stop signal
            stop_event.wait(timeout=cfg.POLL_INTERVAL_MINUTES * 60)

    except Exception as e:
        log_queue.put({
            "type": "error",
            "timestamp": datetime.now().isoformat(),
            "level": "ERROR",
            "message": f"Monitor crashed: {e}",
        })
    finally:
        monitor_running = False
        log_queue.put({
            "type": "status",
            "timestamp": datetime.now().isoformat(),
            "level": "INFO",
            "message": "Monitor stopped.",
        })


# ---------------------------------------------------------------------------
# Flask routes
# ---------------------------------------------------------------------------

@app.route("/")
def index():
    return render_template_string(HTML_TEMPLATE)


@app.route("/api/status")
def api_status():
    setup = _get_setup_status()
    return jsonify({
        "running": monitor_running,
        "setup": setup,
    })


@app.route("/api/alerts")
def api_alerts():
    return jsonify(_load_alerts())


@app.route("/api/save-config", methods=["POST"])
def api_save_config():
    data = request.json
    env = _read_env()

    if "anthropic_key" in data:
        env["ANTHROPIC_API_KEY"] = data["anthropic_key"]
    if "inbox_1" in data:
        env["INBOX_1_EMAIL"] = data["inbox_1"]
    if "inbox_2" in data:
        env["INBOX_2_EMAIL"] = data["inbox_2"]
    if "poll_interval" in data:
        env["POLL_INTERVAL_MINUTES"] = str(data["poll_interval"])

    # Ensure defaults
    env.setdefault("GOOGLE_CREDENTIALS_PATH", "credentials/google-credentials.json")
    env.setdefault("SHEET_ID_INVOICE", "")
    env.setdefault("SHEET_ID_KEVIN", "")

    _write_env(env)
    return jsonify({"ok": True})


@app.route("/api/start", methods=["POST"])
def api_start():
    global monitor_thread
    if monitor_running:
        return jsonify({"ok": False, "error": "Already running"})

    monitor_thread = threading.Thread(target=_run_monitor, daemon=True)
    monitor_thread.start()
    return jsonify({"ok": True})


@app.route("/api/stop", methods=["POST"])
def api_stop():
    if not monitor_running:
        return jsonify({"ok": False, "error": "Not running"})
    stop_event.set()
    return jsonify({"ok": True})


@app.route("/api/stream")
def api_stream():
    """Server-Sent Events endpoint for live log streaming."""
    def generate():
        while True:
            try:
                item = log_queue.get(timeout=30)
                yield f"data: {json.dumps(item)}\n\n"
            except queue.Empty:
                yield f"data: {json.dumps({'type': 'heartbeat'})}\n\n"

    return Response(generate(), mimetype="text/event-stream")


# ---------------------------------------------------------------------------
# HTML Template (single-page app)
# ---------------------------------------------------------------------------

HTML_TEMPLATE = r"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>RotoMath</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
<style>
  * { margin: 0; padding: 0; box-sizing: border-box; }
  body {
    font-family: 'Inter', -apple-system, BlinkMacSystemFont, sans-serif;
    background: #0a0a0a;
    color: #e0e0e0;
    min-height: 100vh;
  }
  /* Header */
  .header {
    background: #111;
    border-bottom: 1px solid #222;
    padding: 1rem 2rem;
    display: flex;
    align-items: center;
    justify-content: space-between;
  }
  .header h1 { font-size: 1.2rem; font-weight: 700; color: #fff; }
  .header .status {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    font-size: 0.8rem;
    font-weight: 600;
  }
  .status-dot {
    width: 8px; height: 8px;
    border-radius: 50%;
    background: #555;
  }
  .status-dot.running { background: #4ade80; box-shadow: 0 0 8px #4ade8066; }
  .status-dot.stopped { background: #f87171; }

  /* Main layout */
  .main {
    display: flex;
    height: calc(100vh - 57px);
  }
  .sidebar {
    width: 320px;
    background: #111;
    border-right: 1px solid #222;
    padding: 1.5rem;
    overflow-y: auto;
    flex-shrink: 0;
  }
  .content {
    flex: 1;
    padding: 1.5rem 2rem;
    overflow-y: auto;
  }

  /* Tabs */
  .tabs {
    display: flex;
    gap: 0;
    margin-bottom: 1.5rem;
    border-bottom: 1px solid #222;
  }
  .tab {
    padding: 0.6rem 1.25rem;
    font-size: 0.8rem;
    font-weight: 600;
    color: #666;
    cursor: pointer;
    border-bottom: 2px solid transparent;
    transition: all 0.15s;
  }
  .tab:hover { color: #aaa; }
  .tab.active { color: #fff; border-bottom-color: #fff; }

  /* Setup form */
  .form-group { margin-bottom: 1.25rem; }
  .form-group label {
    display: block;
    font-size: 0.7rem;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 0.06em;
    color: #666;
    margin-bottom: 0.3rem;
  }
  .form-group input, .form-group select {
    width: 100%;
    background: #0a0a0a;
    border: 1px solid #333;
    border-radius: 8px;
    color: #e0e0e0;
    font-family: 'Inter', sans-serif;
    font-size: 0.85rem;
    padding: 0.55rem 0.75rem;
  }
  .form-group input:focus, .form-group select:focus { outline: none; border-color: #555; }
  .form-group .hint {
    font-size: 0.7rem;
    color: #555;
    margin-top: 0.25rem;
  }
  .check-item {
    display: flex;
    align-items: center;
    gap: 0.5rem;
    font-size: 0.8rem;
    margin-bottom: 0.5rem;
  }
  .check-icon { font-size: 1rem; }
  .check-icon.ok { color: #4ade80; }
  .check-icon.missing { color: #f87171; }

  /* Buttons */
  .btn {
    display: inline-flex;
    align-items: center;
    gap: 0.4rem;
    padding: 0.6rem 1.5rem;
    border: none;
    border-radius: 8px;
    font-family: 'Inter', sans-serif;
    font-size: 0.85rem;
    font-weight: 600;
    cursor: pointer;
    transition: all 0.15s;
  }
  .btn-primary { background: #fff; color: #000; }
  .btn-primary:hover { background: #ddd; }
  .btn-primary:disabled { background: #444; color: #888; cursor: not-allowed; }
  .btn-danger { background: #dc2626; color: #fff; }
  .btn-danger:hover { background: #b91c1c; }
  .btn-save { background: #333; color: #e0e0e0; }
  .btn-save:hover { background: #444; }

  /* Alert cards */
  .alert-card {
    background: #1a1a1a;
    border-left: 3px solid #f87171;
    border-radius: 0 10px 10px 0;
    padding: 1rem 1.25rem;
    margin-bottom: 0.75rem;
  }
  .alert-card .alert-header {
    display: flex;
    justify-content: space-between;
    align-items: baseline;
    margin-bottom: 0.5rem;
  }
  .alert-card .freelancer {
    font-size: 0.95rem;
    font-weight: 600;
    color: #fff;
  }
  .alert-card .timestamp {
    font-size: 0.7rem;
    color: #555;
  }
  .alert-card .amounts {
    display: flex;
    gap: 1.5rem;
    margin-bottom: 0.5rem;
    font-size: 0.8rem;
  }
  .alert-card .amount-label { color: #888; }
  .alert-card .amount-value { font-weight: 600; color: #e0e0e0; }
  .alert-card .amount-value.diff { color: #f87171; font-weight: 700; }
  .alert-card .meta {
    font-size: 0.7rem;
    color: #555;
  }
  .alert-card .line-items {
    margin-top: 0.5rem;
    padding-top: 0.5rem;
    border-top: 1px solid #2a2a2a;
    font-size: 0.75rem;
    color: #888;
    display: none;
  }
  .alert-card .line-items.open { display: block; }
  .alert-card .toggle-items {
    font-size: 0.7rem;
    color: #555;
    cursor: pointer;
    margin-top: 0.4rem;
  }
  .alert-card .toggle-items:hover { color: #888; }

  /* Empty state */
  .empty {
    text-align: center;
    padding: 3rem 1rem;
    color: #444;
    font-size: 0.9rem;
  }

  /* Log stream */
  .log-stream {
    background: #0a0a0a;
    border: 1px solid #222;
    border-radius: 10px;
    padding: 1rem;
    font-family: 'JetBrains Mono', 'Fira Code', 'SF Mono', monospace;
    font-size: 0.72rem;
    line-height: 1.6;
    max-height: 400px;
    overflow-y: auto;
    color: #888;
  }
  .log-line { white-space: pre-wrap; word-break: break-all; }
  .log-line.error { color: #f87171; }
  .log-line.warning { color: #fbbf24; }

  /* Section headers */
  .section-header {
    font-size: 0.7rem;
    font-weight: 700;
    text-transform: uppercase;
    letter-spacing: 0.06em;
    color: #555;
    margin-bottom: 0.75rem;
    margin-top: 1.5rem;
  }
  .section-header:first-child { margin-top: 0; }

  .tab-panel { display: none; }
  .tab-panel.active { display: block; }

  .alert-count-badge {
    background: #dc2626;
    color: #fff;
    font-size: 0.6rem;
    font-weight: 700;
    padding: 0.1rem 0.4rem;
    border-radius: 4px;
    margin-left: 0.3rem;
  }
</style>
</head>
<body>

<div class="header">
  <h1>RotoMath</h1>
  <div class="status">
    <div class="status-dot" id="statusDot"></div>
    <span id="statusText">Checking...</span>
  </div>
</div>

<div class="main">
  <div class="sidebar">
    <div class="section-header">Setup Checklist</div>
    <div id="checklist"></div>

    <div class="section-header">Configuration</div>
    <div class="form-group">
      <label>Anthropic API Key</label>
      <input type="password" id="anthropicKey" placeholder="sk-ant-...">
    </div>
    <div class="form-group">
      <label>Inbox 1 Email</label>
      <input type="email" id="inbox1" placeholder="invoice@example.com">
    </div>
    <div class="form-group">
      <label>Inbox 2 Email</label>
      <input type="email" id="inbox2" placeholder="kevin@example.com">
    </div>
    <div class="form-group">
      <label>Poll Interval (minutes)</label>
      <input type="number" id="pollInterval" value="5" min="1" max="60">
    </div>
    <div class="form-group">
      <label>Google Credentials</label>
      <div class="hint">Place your <code>google-credentials.json</code> file in the <code>credentials/</code> folder.</div>
    </div>

    <div style="display:flex; gap:0.5rem; margin-top:1rem;">
      <button class="btn btn-save" onclick="saveConfig()">Save Config</button>
      <button class="btn btn-primary" id="startBtn" onclick="startMonitor()">Start</button>
      <button class="btn btn-danger" id="stopBtn" onclick="stopMonitor()" style="display:none;">Stop</button>
    </div>
  </div>

  <div class="content">
    <div class="tabs">
      <div class="tab active" data-tab="alerts" onclick="switchTab('alerts')">
        Discrepancy Alerts <span class="alert-count-badge" id="alertBadge" style="display:none;">0</span>
      </div>
      <div class="tab" data-tab="log" onclick="switchTab('log')">Live Log</div>
    </div>

    <div class="tab-panel active" id="panel-alerts">
      <div id="alertsList"><div class="empty">No discrepancy alerts yet. Start the monitor to begin scanning inboxes.</div></div>
    </div>

    <div class="tab-panel" id="panel-log">
      <div class="log-stream" id="logStream">Waiting for monitor to start...</div>
    </div>
  </div>
</div>

<script>
// State
let currentTab = 'alerts';
let eventSource = null;

// Tab switching
function switchTab(tab) {
  currentTab = tab;
  document.querySelectorAll('.tab').forEach(t => t.classList.toggle('active', t.dataset.tab === tab));
  document.querySelectorAll('.tab-panel').forEach(p => p.classList.toggle('active', p.id === 'panel-' + tab));
}

// Status polling
async function refreshStatus() {
  try {
    const res = await fetch('/api/status');
    const data = await res.json();

    const dot = document.getElementById('statusDot');
    const text = document.getElementById('statusText');
    const startBtn = document.getElementById('startBtn');
    const stopBtn = document.getElementById('stopBtn');

    if (data.running) {
      dot.className = 'status-dot running';
      text.textContent = 'Running';
      startBtn.style.display = 'none';
      stopBtn.style.display = '';
    } else {
      dot.className = 'status-dot stopped';
      text.textContent = 'Stopped';
      startBtn.style.display = '';
      stopBtn.style.display = 'none';
    }

    // Populate form if empty
    const s = data.setup;
    if (s.inbox_1 && !document.getElementById('inbox1').value) document.getElementById('inbox1').value = s.inbox_1;
    if (s.inbox_2 && !document.getElementById('inbox2').value) document.getElementById('inbox2').value = s.inbox_2;
    if (s.poll_interval) document.getElementById('pollInterval').value = s.poll_interval;

    // Checklist
    const checks = [
      { label: 'Anthropic API Key', ok: s.anthropic_key },
      { label: 'Google credentials file', ok: s.google_creds_file },
      { label: 'Inbox 1 configured', ok: !!s.inbox_1 },
      { label: 'Inbox 2 configured', ok: !!s.inbox_2 },
      { label: 'Gmail token (Inbox 1)', ok: s.token_invoice },
      { label: 'Gmail token (Inbox 2)', ok: s.token_kevin },
      { label: 'Sheet ID (Inbox 1)', ok: s.sheet_invoice },
      { label: 'Sheet ID (Inbox 2)', ok: s.sheet_kevin },
    ];
    document.getElementById('checklist').innerHTML = checks.map(c =>
      `<div class="check-item">
        <span class="check-icon ${c.ok ? 'ok' : 'missing'}">${c.ok ? '✓' : '✗'}</span>
        <span>${c.label}</span>
      </div>`
    ).join('');

    startBtn.disabled = !s.all_required;

  } catch (e) {
    console.error('Status fetch failed:', e);
  }
}

// Alerts
async function refreshAlerts() {
  try {
    const res = await fetch('/api/alerts');
    const alerts = await res.json();

    const badge = document.getElementById('alertBadge');
    if (alerts.length > 0) {
      badge.textContent = alerts.length;
      badge.style.display = '';
    } else {
      badge.style.display = 'none';
    }

    if (alerts.length === 0) {
      document.getElementById('alertsList').innerHTML =
        '<div class="empty">No discrepancy alerts yet. Start the monitor to begin scanning inboxes.</div>';
      return;
    }

    document.getElementById('alertsList').innerHTML = alerts.map((a, i) => {
      const ts = new Date(a.timestamp).toLocaleString();
      const items = (a.line_items || []).map(li =>
        `${li.description || 'Item'}: $${(li.amount || 0).toFixed(2)}`
      ).join('\n');

      return `<div class="alert-card">
        <div class="alert-header">
          <span class="freelancer">${esc(a.freelancer)}</span>
          <span class="timestamp">${ts}</span>
        </div>
        <div class="amounts">
          <span><span class="amount-label">Stated: </span><span class="amount-value">$${(a.stated_total||0).toFixed(2)}</span></span>
          <span><span class="amount-label">Calculated: </span><span class="amount-value">$${(a.calculated_total||0).toFixed(2)}</span></span>
          <span><span class="amount-label">Difference: </span><span class="amount-value diff">$${(a.discrepancy_amount||0).toFixed(2)}</span></span>
        </div>
        <div class="meta">Source: ${esc(a.source_email)} · ${esc(a.attachment)} · Invoice #${esc(a.invoice_number || 'N/A')}</div>
        <div class="toggle-items" onclick="toggleItems(${i})">Show line items ▾</div>
        <div class="line-items" id="items-${i}"><pre>${esc(items)}</pre></div>
      </div>`;
    }).join('');

  } catch (e) {
    console.error('Alerts fetch failed:', e);
  }
}

function toggleItems(idx) {
  const el = document.getElementById('items-' + idx);
  el.classList.toggle('open');
}

function esc(str) {
  if (!str) return '';
  const div = document.createElement('div');
  div.textContent = str;
  return div.innerHTML;
}

// Config
async function saveConfig() {
  const data = {
    anthropic_key: document.getElementById('anthropicKey').value.trim(),
    inbox_1: document.getElementById('inbox1').value.trim(),
    inbox_2: document.getElementById('inbox2').value.trim(),
    poll_interval: parseInt(document.getElementById('pollInterval').value) || 5,
  };
  await fetch('/api/save-config', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify(data),
  });
  refreshStatus();
}

// Start / Stop
async function startMonitor() {
  await saveConfig();
  await fetch('/api/start', { method: 'POST' });
  setTimeout(refreshStatus, 500);
  startSSE();
}

async function stopMonitor() {
  await fetch('/api/stop', { method: 'POST' });
  setTimeout(refreshStatus, 1000);
}

// SSE live log
function startSSE() {
  if (eventSource) eventSource.close();
  eventSource = new EventSource('/api/stream');
  eventSource.onmessage = function(e) {
    const data = JSON.parse(e.data);
    if (data.type === 'heartbeat') return;

    const stream = document.getElementById('logStream');
    const cls = (data.level === 'ERROR') ? 'error' : (data.level === 'WARNING') ? 'warning' : '';
    const line = document.createElement('div');
    line.className = 'log-line' + (cls ? ' ' + cls : '');
    line.textContent = data.message || JSON.stringify(data);
    stream.appendChild(line);
    stream.scrollTop = stream.scrollHeight;

    // If it's an alert, refresh the alerts panel
    if (data.freelancer || (data.message && data.message.includes('ALERT'))) {
      setTimeout(refreshAlerts, 500);
    }
  };
}

// Init
refreshStatus();
refreshAlerts();
setInterval(refreshStatus, 5000);
setInterval(refreshAlerts, 15000);
</script>
</body>
</html>
"""


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main():
    os.chdir(BASE_DIR)
    os.makedirs(BASE_DIR / "logs", exist_ok=True)
    os.makedirs(BASE_DIR / "credentials", exist_ok=True)
    os.makedirs(BASE_DIR / "token", exist_ok=True)

    # Create .env from example if it doesn't exist
    if not ENV_PATH.exists():
        example = BASE_DIR / ".env.example"
        if example.exists():
            import shutil
            shutil.copy(example, ENV_PATH)

    port = 5123
    print(f"\n{'='*50}")
    print(f"  RotoMath Control Panel")
    print(f"  Opening http://localhost:{port}")
    print(f"  Press Ctrl+C to quit")
    print(f"{'='*50}\n")

    webbrowser.open(f"http://localhost:{port}")
    app.run(host="127.0.0.1", port=port, debug=False, use_reloader=False)


if __name__ == "__main__":
    main()
