/**
 * Mock data for demo/preview mode.
 * Used when no real accounts are connected yet.
 */

export const MOCK_ACCOUNT = {
  id: "mock-account-1",
  email: "ap@gdcgroup.com",
  googleTokens: "mock-tokens",
  cronSchedule: "*/5 * * * *",
  lastRun: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
  nextRun: new Date(Date.now() + 3 * 60 * 1000).toISOString(),
  enabled: true,
  createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  _count: { alerts: 6 },
  rules: [
    { id: "mock-rule-1", ruleType: "date_range" },
    { id: "mock-rule-2", ruleType: "subject_filter" },
    { id: "mock-rule-3", ruleType: "attachment_only" },
  ],
};

export const MOCK_ACCOUNTS_SIMPLE = [
  { id: "mock-account-1", email: "ap@gdcgroup.com" },
];

export const MOCK_RULES = [
  {
    id: "mock-rule-1",
    accountId: "mock-account-1",
    ruleType: "date_range",
    ruleValue: JSON.stringify({ days: 30 }),
    enabled: true,
    createdAt: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "mock-rule-2",
    accountId: "mock-account-1",
    ruleType: "subject_filter",
    ruleValue: JSON.stringify({ contains: "invoice" }),
    enabled: true,
    createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "mock-rule-3",
    accountId: "mock-account-1",
    ruleType: "attachment_only",
    ruleValue: JSON.stringify({ required: true }),
    enabled: true,
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "mock-rule-4",
    accountId: "mock-account-1",
    ruleType: "sender_filter",
    ruleValue: JSON.stringify({ domain: "freelancers.com" }),
    enabled: false,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

export const MOCK_ALERTS = [
  {
    id: "mock-alert-1",
    freelancer: "Sarah Mitchell Design Co.",
    invoiceNumber: "SMD-2026-0147",
    invoiceDate: "2026-03-01",
    statedTotal: 4750.00,
    calculatedTotal: 4550.00,
    discrepancyAmount: 200.00,
    lineItems: JSON.stringify([
      { description: "Brand Identity Package", amount: 2500.00 },
      { description: "Social Media Templates (10)", amount: 850.00 },
      { description: "Business Card Design", amount: 400.00 },
      { description: "Letterhead & Envelope", amount: 350.00 },
      { description: "Style Guide Document", amount: 450.00 },
    ]),
    sourceEmail: "sarah@mitchelldesign.com",
    attachment: "Invoice-SMD-2026-0147.xlsx",
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    account: { email: "ap@gdcgroup.com" },
  },
  {
    id: "mock-alert-2",
    freelancer: "DevOps Solutions LLC",
    invoiceNumber: "DOS-0892",
    invoiceDate: "2026-03-05",
    statedTotal: 12400.00,
    calculatedTotal: 11800.00,
    discrepancyAmount: 600.00,
    lineItems: JSON.stringify([
      { description: "AWS Infrastructure Setup (40 hrs @ $150)", amount: 6000.00 },
      { description: "CI/CD Pipeline Configuration", amount: 2800.00 },
      { description: "Kubernetes Cluster Migration", amount: 1500.00 },
      { description: "Security Audit & Hardening", amount: 1500.00 },
    ]),
    sourceEmail: "billing@devopssolutions.io",
    attachment: "DOS-0892-March.docx",
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    account: { email: "ap@gdcgroup.com" },
  },
  {
    id: "mock-alert-3",
    freelancer: "Jennifer Park Writing",
    invoiceNumber: "JPW-441",
    invoiceDate: "2026-03-08",
    statedTotal: 3200.00,
    calculatedTotal: 2950.00,
    discrepancyAmount: 250.00,
    lineItems: JSON.stringify([
      { description: "Blog Posts (4 × $375)", amount: 1500.00 },
      { description: "Case Study — Enterprise Client", amount: 650.00 },
      { description: "Email Newsletter Copy (8 editions)", amount: 400.00 },
      { description: "Product Description Rewrites", amount: 400.00 },
    ]),
    sourceEmail: "jen@parkwriting.co",
    attachment: "Invoice_JPW-441.xlsx",
    createdAt: new Date(Date.now() - 26 * 60 * 60 * 1000).toISOString(),
    account: { email: "ap@gdcgroup.com" },
  },
  {
    id: "mock-alert-4",
    freelancer: "Marcus Rivera Photography",
    invoiceNumber: "MRP-2026-033",
    invoiceDate: "2026-03-10",
    statedTotal: 5800.00,
    calculatedTotal: 5350.00,
    discrepancyAmount: 450.00,
    lineItems: JSON.stringify([
      { description: "Product Photography (Full Day)", amount: 2200.00 },
      { description: "Photo Editing & Retouching (48 images)", amount: 1440.00 },
      { description: "Lifestyle Shots (Half Day)", amount: 1100.00 },
      { description: "Rush Delivery Surcharge", amount: 610.00 },
    ]),
    sourceEmail: "marcus@riveraphotography.com",
    attachment: "MRP-2026-033.docx",
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    account: { email: "ap@gdcgroup.com" },
  },
  {
    id: "mock-alert-5",
    freelancer: "TechConsult Partners",
    invoiceNumber: "TCP-7821",
    invoiceDate: "2026-02-28",
    statedTotal: 18500.00,
    calculatedTotal: 17250.00,
    discrepancyAmount: 1250.00,
    lineItems: JSON.stringify([
      { description: "Strategic Consulting (25 hrs @ $300)", amount: 7500.00 },
      { description: "System Architecture Review", amount: 4500.00 },
      { description: "Staff Training Workshop (2 days)", amount: 3000.00 },
      { description: "Documentation Package", amount: 2250.00 },
    ]),
    sourceEmail: "invoices@techconsultpartners.com",
    attachment: "TCP-7821-Feb-2026.xlsx",
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    account: { email: "ap@gdcgroup.com" },
  },
  {
    id: "mock-alert-6",
    freelancer: "Priya Sharma Translations",
    invoiceNumber: "PST-0064",
    invoiceDate: "2026-03-11",
    statedTotal: 2100.00,
    calculatedTotal: 1975.00,
    discrepancyAmount: 125.00,
    lineItems: JSON.stringify([
      { description: "Document Translation EN→ES (15 pages)", amount: 675.00 },
      { description: "Document Translation EN→FR (15 pages)", amount: 675.00 },
      { description: "Localization Review & QA", amount: 375.00 },
      { description: "Rush Fee (48-hr turnaround)", amount: 250.00 },
    ]),
    sourceEmail: "priya@sharmatranslations.com",
    attachment: null,
    createdAt: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
    account: { email: "ap@gdcgroup.com" },
  },
];
