/**
 * Mock data for demo/preview mode.
 * Used when no real accounts are connected yet.
 */

export const MOCK_ACCOUNT = {
  id: "mock-account-1",
  email: "ap@gdcgroup.com",
  googleTokens: "mock-tokens",
  cronSchedule: "*/5 * * * *",
  lastRun: new Date(Date.now() - 12 * 60 * 1000).toISOString(),
  nextRun: new Date(Date.now() + 3 * 60 * 1000).toISOString(),
  enabled: true,
  createdAt: new Date(Date.now() - 14 * 24 * 60 * 60 * 1000).toISOString(),
  _count: { alerts: 6 },
  rules: [
    { id: "mock-rule-1", ruleType: "date_range" },
    { id: "mock-rule-2", ruleType: "subject_filter" },
    { id: "mock-rule-3", ruleType: "attachment_only" },
  ],
};

export const MOCK_ACCOUNTS_SIMPLE = [
  { id: "mock-account-1", email: "ap@gdcgroup.com" },
];

export const MOCK_RULES = [
  {
    id: "mock-rule-1",
    accountId: "mock-account-1",
    ruleType: "date_range",
    ruleValue: JSON.stringify({ days: 30 }),
    enabled: true,
    createdAt: new Date(Date.now() - 13 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "mock-rule-2",
    accountId: "mock-account-1",
    ruleType: "subject_filter",
    ruleValue: JSON.stringify({ contains: "invoice" }),
    enabled: true,
    createdAt: new Date(Date.now() - 12 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "mock-rule-3",
    accountId: "mock-account-1",
    ruleType: "attachment_only",
    ruleValue: JSON.stringify({ required: true }),
    enabled: true,
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000).toISOString(),
  },
  {
    id: "mock-rule-4",
    accountId: "mock-account-1",
    ruleType: "sender_filter",
    ruleValue: JSON.stringify({ domain: "freelancers.com" }),
    enabled: false,
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
  },
];

/**
 * Each invoice body line is an object:
 *   { text: string, hasError?: boolean }
 * Lines with hasError: true will be highlighted in pale red on the detail page.
 *
 * Each error is:
 *   { title: string, description: string, severity: "high" | "medium" | "low" }
 */

export const MOCK_ALERTS = [
  {
    id: "mock-alert-1",
    freelancer: "Sarah Mitchell Design Co.",
    invoiceNumber: "SMD-2026-0147",
    invoiceDate: "2026-03-01",
    statedTotal: 4750.00,
    calculatedTotal: 4550.00,
    discrepancyAmount: 200.00,
    lineItems: JSON.stringify([
      { description: "Brand Identity Package", amount: 2500.00 },
      { description: "Social Media Templates (10)", amount: 850.00 },
      { description: "Business Card Design", amount: 400.00 },
      { description: "Letterhead & Envelope", amount: 350.00 },
      { description: "Style Guide Document", amount: 450.00 },
    ]),
    sourceEmail: "sarah@mitchelldesign.com",
    attachment: "Invoice-SMD-2026-0147.xlsx",
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    account: { email: "ap@gdcgroup.com" },
    emailSubject: "Invoice #SMD-2026-0147 for March Design Work",
    invoiceBody: [
      { text: "INVOICE" },
      { text: "" },
      { text: "Sarah Mitchell Design Co." },
      { text: "1204 Creative Blvd, Austin, TX 78701" },
      { text: "sarah@mitchelldesign.com" },
      { text: "" },
      { text: "Invoice #: SMD-2026-0147" },
      { text: "Date: March 1, 2026" },
      { text: "Due: March 31, 2026" },
      { text: "" },
      { text: "Bill To:" },
      { text: "GDC Group — Accounts Payable" },
      { text: "" },
      { text: "─────────────────────────────────────────────" },
      { text: "Description                          Amount" },
      { text: "─────────────────────────────────────────────" },
      { text: "Brand Identity Package              $2,500.00" },
      { text: "Social Media Templates (10)           $850.00" },
      { text: "Business Card Design                  $400.00" },
      { text: "Letterhead & Envelope                 $350.00" },
      { text: "Style Guide Document                  $450.00" },
      { text: "─────────────────────────────────────────────" },
      { text: "TOTAL                               $4,750.00", hasError: true },
      { text: "" },
      { text: "Payment Terms: Net 30" },
    ],
    errors: [
      {
        title: "Invoice total does not match line item sum",
        description: "The stated total is $4,750.00 but the sum of all line items is $4,550.00. The invoice is overstated by $200.00. The line items sum to $2,500 + $850 + $400 + $350 + $450 = $4,550.",
        severity: "high" as const,
      },
    ],
  },
  {
    id: "mock-alert-2",
    freelancer: "DevOps Solutions LLC",
    invoiceNumber: "DOS-0892",
    invoiceDate: "2026-03-05",
    statedTotal: 12400.00,
    calculatedTotal: 11800.00,
    discrepancyAmount: 600.00,
    lineItems: JSON.stringify([
      { description: "AWS Infrastructure Setup (40 hrs @ $150)", amount: 6000.00 },
      { description: "CI/CD Pipeline Configuration", amount: 2800.00 },
      { description: "Kubernetes Cluster Migration", amount: 1500.00 },
      { description: "Security Audit & Hardening", amount: 1500.00 },
    ]),
    sourceEmail: "billing@devopssolutions.io",
    attachment: "DOS-0892-March.docx",
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    account: { email: "ap@gdcgroup.com" },
    emailSubject: "March Invoice DOS-0892 — DevOps Solutions",
    invoiceBody: [
      { text: "DevOps Solutions LLC" },
      { text: "Invoice #DOS-0892" },
      { text: "Date: March 5, 2026" },
      { text: "" },
      { text: "Client: GDC Group" },
      { text: "Project: Cloud Infrastructure Modernization" },
      { text: "" },
      { text: "Services Rendered:" },
      { text: "" },
      { text: "1. AWS Infrastructure Setup" },
      { text: "   40 hours @ $150/hr                $6,000.00" },
      { text: "" },
      { text: "2. CI/CD Pipeline Configuration      $2,800.00" },
      { text: "" },
      { text: "3. Kubernetes Cluster Migration       $1,500.00" },
      { text: "" },
      { text: "4. Security Audit & Hardening         $1,500.00" },
      { text: "" },
      { text: "────────────────────────────────────────" },
      { text: "Subtotal                            $11,800.00" },
      { text: "Platform Fee (5%)                      $600.00", hasError: true },
      { text: "────────────────────────────────────────" },
      { text: "TOTAL DUE                           $12,400.00", hasError: true },
      { text: "" },
      { text: "Wire to: Chase Business Acct ending 4821" },
    ],
    errors: [
      {
        title: "Unlisted fee inflates total",
        description: "A 'Platform Fee (5%)' of $600.00 is included in the total but was not part of the agreed line items. The contracted work totals $11,800.00 but the invoice charges $12,400.00.",
        severity: "high" as const,
      },
      {
        title: "Platform fee not in original scope",
        description: "The platform fee was not mentioned in the original SOW or contract. This surcharge should be verified with the project manager before payment.",
        severity: "medium" as const,
      },
    ],
  },
  {
    id: "mock-alert-3",
    freelancer: "Jennifer Park Writing",
    invoiceNumber: "JPW-441",
    invoiceDate: "2026-03-08",
    statedTotal: 3200.00,
    calculatedTotal: 2950.00,
    discrepancyAmount: 250.00,
    lineItems: JSON.stringify([
      { description: "Blog Posts (4 × $375)", amount: 1500.00 },
      { description: "Case Study — Enterprise Client", amount: 650.00 },
      { description: "Email Newsletter Copy (8 editions)", amount: 400.00 },
      { description: "Product Description Rewrites", amount: 400.00 },
    ]),
    sourceEmail: "jen@parkwriting.co",
    attachment: "Invoice_JPW-441.xlsx",
    createdAt: new Date(Date.now() - 26 * 60 * 60 * 1000).toISOString(),
    account: { email: "ap@gdcgroup.com" },
    emailSubject: "Invoice JPW-441 — March Content Deliverables",
    invoiceBody: [
      { text: "Jennifer Park Writing Services" },
      { text: "jen@parkwriting.co | (512) 555-0198" },
      { text: "" },
      { text: "Invoice #JPW-441         Date: March 8, 2026" },
      { text: "" },
      { text: "To: GDC Group — Marketing Dept." },
      { text: "" },
      { text: "Item                                  Amount" },
      { text: "───────────────────────────────────────────" },
      { text: "Blog Posts (4 × $375)               $1,500.00" },
      { text: "Case Study — Enterprise Client        $650.00" },
      { text: "Email Newsletter Copy (8 editions)    $400.00" },
      { text: "Product Description Rewrites          $400.00" },
      { text: "───────────────────────────────────────────" },
      { text: "Subtotal                            $2,950.00" },
      { text: "Revision Fee                          $250.00", hasError: true },
      { text: "───────────────────────────────────────────" },
      { text: "TOTAL                               $3,200.00", hasError: true },
      { text: "" },
      { text: "Please remit within 30 days." },
    ],
    errors: [
      {
        title: "Unexpected revision fee added",
        description: "A $250.00 'Revision Fee' was added that doesn't correspond to any line item in the agreed scope. The line items total $2,950.00 but the invoice states $3,200.00.",
        severity: "high" as const,
      },
    ],
  },
  {
    id: "mock-alert-4",
    freelancer: "Marcus Rivera Photography",
    invoiceNumber: "MRP-2026-033",
    invoiceDate: "2026-03-10",
    statedTotal: 5800.00,
    calculatedTotal: 5350.00,
    discrepancyAmount: 450.00,
    lineItems: JSON.stringify([
      { description: "Product Photography (Full Day)", amount: 2200.00 },
      { description: "Photo Editing & Retouching (48 images)", amount: 1440.00 },
      { description: "Lifestyle Shots (Half Day)", amount: 1100.00 },
      { description: "Rush Delivery Surcharge", amount: 610.00 },
    ]),
    sourceEmail: "marcus@riveraphotography.com",
    attachment: "MRP-2026-033.docx",
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    account: { email: "ap@gdcgroup.com" },
    emailSubject: "Invoice MRP-2026-033 — Product Shoot for GDC",
    invoiceBody: [
      { text: "MARCUS RIVERA PHOTOGRAPHY" },
      { text: "marcus@riveraphotography.com" },
      { text: "" },
      { text: "Invoice: MRP-2026-033" },
      { text: "Date: March 10, 2026" },
      { text: "Client: GDC Group" },
      { text: "" },
      { text: "──────────────────────────────────────────" },
      { text: "Product Photography (Full Day)      $2,200.00" },
      { text: "Photo Editing & Retouching" },
      { text: "  48 images × $30/image             $1,440.00" },
      { text: "Lifestyle Shots (Half Day)          $1,100.00" },
      { text: "Rush Delivery Surcharge               $610.00", hasError: true },
      { text: "──────────────────────────────────────────" },
      { text: "TOTAL                               $5,800.00", hasError: true },
      { text: "" },
      { text: "Note: Rush surcharge reflects 24hr turnaround" },
      { text: "for edited deliverables." },
    ],
    errors: [
      {
        title: "Rush surcharge inflated",
        description: "The 'Rush Delivery Surcharge' is listed as $610.00 but the actual line items sum to $5,350.00, meaning the total of $5,800.00 is overstated by $450.00. The surcharge appears to have been increased from an expected ~$160 to $610.",
        severity: "high" as const,
      },
      {
        title: "Total does not match sum of line items",
        description: "Sum of $2,200 + $1,440 + $1,100 + $610 = $5,350, not $5,800 as stated. There is an unaccounted $450 in the total.",
        severity: "high" as const,
      },
    ],
  },
  {
    id: "mock-alert-5",
    freelancer: "TechConsult Partners",
    invoiceNumber: "TCP-7821",
    invoiceDate: "2026-02-28",
    statedTotal: 18500.00,
    calculatedTotal: 17250.00,
    discrepancyAmount: 1250.00,
    lineItems: JSON.stringify([
      { description: "Strategic Consulting (25 hrs @ $300)", amount: 7500.00 },
      { description: "System Architecture Review", amount: 4500.00 },
      { description: "Staff Training Workshop (2 days)", amount: 3000.00 },
      { description: "Documentation Package", amount: 2250.00 },
    ]),
    sourceEmail: "invoices@techconsultpartners.com",
    attachment: "TCP-7821-Feb-2026.xlsx",
    createdAt: new Date(Date.now() - 5 * 24 * 60 * 60 * 1000).toISOString(),
    account: { email: "ap@gdcgroup.com" },
    emailSubject: "TechConsult Partners — February Invoice TCP-7821",
    invoiceBody: [
      { text: "TechConsult Partners" },
      { text: "Enterprise Technology Advisory" },
      { text: "invoices@techconsultpartners.com" },
      { text: "" },
      { text: "INVOICE TCP-7821" },
      { text: "Period: February 2026" },
      { text: "Client: GDC Group" },
      { text: "" },
      { text: "Description                            Amount" },
      { text: "─────────────────────────────────────────────" },
      { text: "Strategic Consulting" },
      { text: "  25 hours @ $300/hr                 $7,500.00" },
      { text: "" },
      { text: "System Architecture Review            $4,500.00" },
      { text: "" },
      { text: "Staff Training Workshop (2 days)      $3,000.00" },
      { text: "" },
      { text: "Documentation Package                 $2,250.00" },
      { text: "─────────────────────────────────────────────" },
      { text: "Subtotal                            $17,250.00" },
      { text: "After-hours Support (estimated)      $1,250.00", hasError: true },
      { text: "─────────────────────────────────────────────" },
      { text: "TOTAL DUE                           $18,500.00", hasError: true },
      { text: "" },
      { text: "Terms: Net 15 | Late fee: 1.5%/month" },
    ],
    errors: [
      {
        title: "Unverified after-hours support charge",
        description: "An 'After-hours Support (estimated)' charge of $1,250.00 was added that isn't backed by any line-item detail or timesheet. This is the largest discrepancy in the current batch.",
        severity: "high" as const,
      },
      {
        title: "Charge labeled as 'estimated'",
        description: "The after-hours charge is explicitly labeled 'estimated', meaning the vendor hasn't confirmed the actual amount. This should be reconciled with actual hours before payment.",
        severity: "medium" as const,
      },
    ],
  },
  {
    id: "mock-alert-6",
    freelancer: "Priya Sharma Translations",
    invoiceNumber: "PST-0064",
    invoiceDate: "2026-03-11",
    statedTotal: 2100.00,
    calculatedTotal: 1975.00,
    discrepancyAmount: 125.00,
    lineItems: JSON.stringify([
      { description: "Document Translation EN→ES (15 pages)", amount: 675.00 },
      { description: "Document Translation EN→FR (15 pages)", amount: 675.00 },
      { description: "Localization Review & QA", amount: 375.00 },
      { description: "Rush Fee (48-hr turnaround)", amount: 250.00 },
    ]),
    sourceEmail: "priya@sharmatranslations.com",
    attachment: null,
    createdAt: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
    account: { email: "ap@gdcgroup.com" },
    emailSubject: "Translation Invoice PST-0064",
    invoiceBody: [
      { text: "Priya Sharma Translations" },
      { text: "priya@sharmatranslations.com" },
      { text: "" },
      { text: "Invoice #PST-0064" },
      { text: "Date: March 11, 2026" },
      { text: "" },
      { text: "To: GDC Group" },
      { text: "" },
      { text: "Services:" },
      { text: "  Document Translation EN→ES" },
      { text: "    15 pages @ $45/page                $675.00" },
      { text: "  Document Translation EN→FR" },
      { text: "    15 pages @ $45/page                $675.00" },
      { text: "  Localization Review & QA             $375.00" },
      { text: "  Rush Fee (48-hr turnaround)          $250.00" },
      { text: "" },
      { text: "──────────────────────────────────────────" },
      { text: "Subtotal                             $1,975.00" },
      { text: "Tax (estimated)                        $125.00", hasError: true },
      { text: "──────────────────────────────────────────" },
      { text: "TOTAL                                $2,100.00", hasError: true },
      { text: "" },
      { text: "Venmo: @priya-sharma-tx" },
    ],
    errors: [
      {
        title: "Tax charge may not apply",
        description: "A $125.00 tax charge is added to the total, but translation services from freelance contractors are typically not subject to sales tax. The line items sum to $1,975.00 and the stated total is $2,100.00.",
        severity: "medium" as const,
      },
    ],
  },
];

/** Notifications for the bell icon */
export const MOCK_NOTIFICATIONS = [
  {
    id: "notif-1",
    alertId: "mock-alert-1",
    title: "New discrepancy: Sarah Mitchell Design Co.",
    message: "Invoice SMD-2026-0147 is overstated by $200.00",
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    read: false,
  },
  {
    id: "notif-2",
    alertId: "mock-alert-2",
    title: "New discrepancy: DevOps Solutions LLC",
    message: "Invoice DOS-0892 includes an unlisted $600 platform fee",
    createdAt: new Date(Date.now() - 8 * 60 * 60 * 1000).toISOString(),
    read: false,
  },
  {
    id: "notif-3",
    alertId: "mock-alert-6",
    title: "New discrepancy: Priya Sharma Translations",
    message: "Invoice PST-0064 includes a possibly incorrect $125 tax charge",
    createdAt: new Date(Date.now() - 18 * 60 * 60 * 1000).toISOString(),
    read: false,
  },
  {
    id: "notif-4",
    alertId: "mock-alert-3",
    title: "New discrepancy: Jennifer Park Writing",
    message: "Invoice JPW-441 has an unexpected $250 revision fee",
    createdAt: new Date(Date.now() - 26 * 60 * 60 * 1000).toISOString(),
    read: true,
  },
  {
    id: "notif-5",
    alertId: "mock-alert-4",
    title: "New discrepancy: Marcus Rivera Photography",
    message: "Invoice MRP-2026-033 is overstated by $450.00",
    createdAt: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    read: true,
  },
];
